// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiEtl.Infrastructure.Database;

#nullable disable

namespace NycTaxiEtl.Migrations
{
    [DbContext(typeof(TaxiDbContext))]
    partial class TaxiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiEtl.Domain.Entities.TaxiRide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("DOLocationID")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("DropoffDatetimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<short>("PULocationID")
                        .HasColumnType("smallint");

                    b.Property<byte>("PassengerCount")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("PickupDatetimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TripDistance")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PULocationID")
                        .HasDatabaseName("IX_TaxiRides_PULocationID");

                    b.HasIndex("TripDistance")
                        .IsDescending()
                        .HasDatabaseName("IX_TaxiRides_TripDistance_Desc");

                    b.HasIndex("PickupDatetimeUtc", "DropoffDatetimeUtc")
                        .HasDatabaseName("IX_TaxiRides_Pickup_Dropoff");

                    b.ToTable("TaxiRides", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
